server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    accept-count: 100
    connection-timeout: PT5S
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: fh9421
    initialization-mode: always
    schema: classpath:sql/initialize.sql
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true